.github/workflows/publish.yml
When the trigger is a tag event, the tag is already there, so passing --tags to git fetch causes it to fail.
Remove the commit to main event because we do not need to publish images for every single change that makes it to main, only for the ones that get published.
=> fix: do not fetch tags

Dockerfile, lib/get-latest-gbt-version, lib/image-test
This small script can be used to find the most recent release of grafana-build-tools. Client repositories can use this to figure out if their version is up-to-date.
=> Add get-latest-gbt-version

Dockerfile
It seems like there's an issue if you run golangci-lint binaries with go compiler versions different than the one that was used to build it.
=> Build golangci-lint from source

.github/workflows/pr.yml
056dd80d57d54dda40af558cb2f9c714127b6721 changed how things work, the Dockerfile is no longer part of the repo, it's generated from Dockerfile.tmpl and versions.yaml.
=> Update pull request workflow

Dockerfile.tmpl
Split build into multiple stages, one for each tool, and generate the final part so that the binaries are copied.
This has better caching behavior.
=> Reorganize Dockerfile.tmpl

.github/workflows/buildkitd.toml, .github/workflows/publish.yml
For whatever reason, the build is failing after introducing more stages. I suspect it's because there are more stages than whatever buildkit is using for paralellism, and it's hitting some limit elsewhere.
=> Limit build paralellism

scripts/release
`make build-local` doesn't build create a container image, it simply builds the binaries. `make image-local` takes those binaries and creates an image with them.
The release script needs git-chglog to create the CHANGELOG.md file, and instead of assuming it's available locally, it uses the one that is part of the container image. It's a bit heavy-handed, but it gets the job done.
=> Fix: release script should use `make image-local`

.github/renovate.json, .github/workflows/renovate.yaml
Renovate broke something and the absence of docker digest is causing it to fail with some unrelated "cannot create branch error".
Just disable it.
=> Disable pinning of docker dependencies

.github/workflows/renovate.yaml
Mostly a precaution.
https://github.com/actions/checkout/issues/485
=> Set persist-credentials to false

CHANGELOG.md
* Update dependency xk6 to v0.13.4 (#226)
* Update dependency lefthook to v1.10.0 (#220)
* Set persist-credentials to false (#230)
* Update dependency golangci-lint to v1.63.4 (#223)
* Update dependency chglog to v0.6.2 (#228)
* Update dependency lefthook to v1.10.2 (#229)
* Update dependency buf to v1.48.0 (#219)
* Update dependency lefthook to v1.10.4 (#233)
* Update dependency yq to v4.45.1 (#232)
* Update dependency nfpm to v2.41.2 (#231)
=> Release v0.36.0

Dockerfile.build.tmpl, lib/image-test, versions.yaml
Because of a recent security incident involving reviewdog, remove this program from the image.
=> Remove reviewdog

.github/renovate.json
As with so many other things renovate, this is likely not going to do what I'm expecting...
=> fix: Add automerge settings to renovate configuration

Dockerfile.build.tmpl, lib/image-test, versions.yaml
Keep golangci-lint in the image to avoid breaking backwards compatibility with existing users. Add golangci-lint-v2 to create an upgrade path.
=> feat: Add golangci-lint-v2

CHANGELOG.md
* fix: Handle different architectures when renaming golangci-lint
=> Release v1.7.2

Dockerfile.tmpl, build/spectral, lib/image-test, versions.yaml
Related to https://github.com/grafana/synthetic-monitoring-api/issues/1512
Spectral is a JSON/YAML linter with OOTB support for OpenAPI 3.x.
Add it to the image so we can use it in linting steps for the Synthetic Monitoring OpenAPI spec.
This is needed so I can get https://github.com/grafana/synthetic-monitoring-api/pull/1548 working in CI. I think the docker-in-docker situation is getting in the way of easily using the `stoplight/spectral` image to lint in CI.
=> feat: Add Spectral to the image

CHANGELOG.md
* feat: Update to Go 1.25.0
The commit that updates Go to 1.25.0 states that wire was removed. This is incorrect.
=> Release v1.18.0

CHANGELOG.md
* chore: Update dependency gotest.tools/gotestsum to v1.13.0 (#412)
* chore: Update dependency xk6 to v1.1.4 (#413)
* chore: Update dependency lefthook to v1.13.0 (#414)
* chore: Update dependency buf to v1.57.2 (#415)
* chore: Update dependency lefthook to v1.13.1 (#416)
=> Release v1.20.0

.github/renovate.json, .github/renovate.yaml, Dockerfile.tmpl, scripts/enforce-clean, versions.yaml
Rework versions.yaml so that it contains more information about the individual packages. This makes the Dockerfile.tmpl file cleaner. Update the renovate configuration to match, and clean it up in the process, too.
=> fix: rework versions file

.github/renovate.json, .github/renovate.yaml, .github/workflows/renovate.yaml, .github/workflows/validate-renovate-config.yaml
cd61ee04b4cd1d378e1ecad45bace6da8a951259 updated the renovate version from 39.23.0 to 41.97.0. Move back to the previous value to see if this gets rid of a strange behavior where it's updating (mixing up) the depName to something non-sensical.
=> fix: Move renovate back to 39.23.0

.github/renovate.yaml
Something is seriously confusing renovate and it's trying to update the *next* matching string, causing a useless error "depName mismatch", where the current name is "go" and the "new" name is "jq". If you look at the file, go comes first and jq is the next match for the docker group.
=> fix: Change renovate regular expressions
