grafana/grafana-build-tools

- CHANGELOG.md
> Release v0.1.2

- Dockerfile.tmpl
- Makefile
- versions.yaml
This paves the way to write a tool that can check if there are any updates available.
> Add versions.yaml file to capture versions of tools

- versions.yaml
This is more groundwork for creating a tool that can update the file.
> Annotate versions.yaml with type information

- CHANGELOG.md
> Release v0.6.1

- Dockerfile
- versions.yaml
- buf v1.29.0
- enumer v1.5.9
- golangci-lint v1.55.2
- jq 1.7.1
- nilaway v0.0.0-20231117175943-a267567c6fff
- protobuf v1.32.0
- wire v0.6.0
- xk6 v0.11.0
> Upgrade tools

- Dockerfile
- Dockerfile.tmpl
- lib/image-test
- versions.yaml
This tool reads a Dockerfile and spits out the corresponding JSON representation (using the official parser code).
> Add dockerfile-json

- CHANGELOG.md
> Release v0.10.1

- Dockerfile
- Makefile
- versions.yaml
* github.com/bufbuild/buf: v1.33.0 -> v1.34.0
* github.com/grafana/k6: v0.51.0 -> v0.52.0
> Update tool versions

- CHANGELOG.md
> Release v0.15.1

- CHANGELOG.md
> Release v0.17.1

- .github/workflows/renovate.yaml
41 is prime. Prime is nice. It avoids the rush at 0 minutes. And at 30 minutes. And at 45 minutes.
> Trigger renovate workflow on a schedule

- CHANGELOG.md
* Limit build paralellism
* Rework build to avoid emulation
* Test if limiting build parallelism is still necesary
> Release v0.19.1

- .github/workflows/publish.yml
It sounds like fetch tags is not needed?
https://github.com/actions/checkout/issues/1467
> Fix error when fetching tags

- CHANGELOG.md
* Fix error when fetching tags
> Release v0.19.2

- CHANGELOG.md
> Release v0.23.1

- .whitesource
Since the app is enabled for the organization, and it seems to have access to all repos, every now and then we get PRs from Mend, which is annoying.
Add a configuration file to disable that.
> Turn off Remediate (Mend Renovate)

- CHANGELOG.md
* Upgrade buf to v1.40.0
* Update lefthook to v1.7.15
* Turn off Remediate (Mend Renovate)
* Update renovate configuration
* Go back to platformCommit: true
* Update dependency xk6 to v0.13.0
* Update dependency actionlint to v1.7.2
* Update go Docker tag to v1.23.2
> Release v0.24.0

- CHANGELOG.md
* Update dependency buf to v1.45.0
> Release v0.29.0

- CHANGELOG.md
* Update dependency lefthook to v1.8.2
> Release v0.29.1

- Dockerfile.build.tmpl
- lib/image-test
- versions.yaml
I was 100% sure this was already here.
> Add gomplate

- CHANGELOG.md
> Release v0.30.0

- CHANGELOG.md
* Dockerfile: add curl
* lib/image-test: ensure that curl exists and is runnable
* Update dependency actionlint to v1.7.4
* Update dependency buf to v1.46.0
* Feature: add gh
* Feature: add oapi-codegen
> Release v0.31.0

- CHANGELOG.md
* Fix: change gh's build so that it works
> Release v0.31.1

- CHANGELOG.md
* Update go Docker tag to v1.23.3
> Release v0.31.2

- CHANGELOG.md
* Update dependency golangci-lint to v1.62.0
* Update dependency gomplate to v4.2.0
* Update dependency dockerfile-json to v1.2.1
> Release v0.32.0

- CHANGELOG.md
* Update go:1.23.3 Docker digest to c2d828f
* Update dependency buf to v1.47.0
* Update go:1.23.3 Docker digest to 73f06be
* Update dependency yq to v4.44.5
* Update dependency buf to v1.47.2 (#190)
* Update module protoc-gen-go to v1.35.2 (#189)
* Update dependency xk6 to v0.13.1 (#195)
* Update dependency nfpm to v2.41.1 (#193)
* Try to disanble renovate bot, again
* Revert "Try to disanble renovate bot, again"
* Another try at disabling renovatebot
* Revert "Another try at disabling renovatebot"
* Disable renovatebot, again
* Add configuration files to disable renovate
* Update renovate version
* Remove version pins
* Fix docker-cmd-file argument
* Change platformCommit from "true" to "enabled"
* Fix renovate.json
* Update dependency lefthook to v1.8.4 (#198)
* Update dependency skopeo …
> Release v0.33.0

- CHANGELOG.md
* Update dependency golangci-lint to v1.62.2 (#202)
> Release v0.33.1

- CHANGELOG.md
* Update dependency reviewdog to v0.20.3 (#207)
* Update dependency yq to v4.44.6 (#208)
* Update go Docker tag to v1.23.4 (#206)
> Release v0.33.2

- CHANGELOG.md
* Update dependency lefthook to v1.9.0 (#204)
* Update dependency lefthook to v1.9.2 (#211)
* Add sqlc (#212)
* Add golang-migrate (#213)
> Release v0.34.0

- CHANGELOG.md
* Update module protoc-gen-go to v1.36.0 (#215)
* Update dependency gomplate to v4.3.0 (#216)
* Update dependency lefthook to v1.9.3 (#217)
* Update dependency k6 to v0.55.1 (#218)
* Update module protoc-gen-go to v1.36.1 (#221)
* Update dependency actionlint to v1.7.5 (#222)
> Release v0.35.0

- CHANGELOG.md
* Update module protoc-gen-go to v1.36.2 (#225)
* Update go:1.23.4 Docker digest to 7003184 (#210)
> Release v0.35.1

- CHANGELOG.md
* Update go:1.23.4 Docker digest to 3b1a7de (#235)
* Update go Docker tag to v1.23.5 (#239)
> Release v0.36.1

- CHANGELOG.md
* Update module protoc-gen-go to v1.36.4 (#246)
* Update dependency migrate to v4.18.2 (#247)
> Release v0.37.1

- CHANGELOG.md
* Update go Docker tag to v1.23.6 (#250)
* Update dependency xk6 to v0.14.0 (#251)
> Release v0.38.0

- CHANGELOG.md
* Update dependency xk6 to v0.14.1 (#255)
* Update module protoc-gen-go to v1.36.5 (#254)
* Update dependency dockerfile-json to v1.2.2 (#252)
> Release v0.38.1

- lib/go.env
Set GOAMD64 to v2 and GOARM64 to v8.0 by default.
> Specify microarchitecture

- CHANGELOG.md
* Specify microarchitecture (#257)
> Release v0.39.0

- CHANGELOG.md
* Update go Docker tag to v1.24.0 (#265)
* Update dependency golangci-lint to v1.64.4 (#258)
* Update dependency k6 to v0.57.0 (#263)
* Update dependency skopeo to v1.18.0 (#260)
> Release v0.40.0

- CHANGELOG.md
* Update dependency golangci-lint to v1.64.5 (#267)
* Update dependency xk6 to v0.14.3 (#268)
> Release v0.40.1

- CHANGELOG.md
* Update dependency golangci-lint to v1.64.6 (#273)
* Update dependency nfpm to v2.41.3
* Update dependency lefthook to v1.11.2
* Update dependency enumer to v1.5.11
> Release v0.40.2

- CHANGELOG.md
* Fix GitHub Action workflow permissions
> Release v1.5.2

- CHANGELOG.md
* Use tag with version for the attestation subject
> Release v1.5.4

- CHANGELOG.md
* Update dependency lefthook to v1.11.13 (#325)
* Fix attestations subject name
> Release v1.5.5

- CHANGELOG.md
* fix: Add policy bot configuration (#330)
* Update dependency nfpm to v2.42.1 (#331)
> Release v1.5.6

- CHANGELOG.md
* fix: Find binaries in /build/, not build/
> Release v1.7.3

- CHANGELOG.md
* feat: Add 7zz to the image
* chore: Update dependency lefthook to v1.12.2
* chore: Update dependency golangci-lint to v2.2.2
* chore: Update dependency yq to v4.46.1 (#360)
> Release v1.10.0

- CHANGELOG.md
* chore: Update dependency wire to v0.7.0 (#395)
* chore: Update module protoc-gen-go to v1.36.8 (#394)
* chore: Update dependency k6 to v1.2.2 (#393)
> Release v1.15.0

- CHANGELOG.md
* fix: Validate policybot config
* chore: Update dependency lefthook to v1.13.5 (#434)
* chore: Update dependency nfpm to v2.43.3 (#438)
* chore: Update module protoc-gen-go to v1.36.10 (#437)
* chore: Update dependency lefthook to v1.13.6 (#435)
* chore: Update go:1.25.1 Docker digest to d709837 (#436)
> Release v1.21.1
